services:
    nginx:
        image: barlito/youl-tcg-showcase:${TAG:-latest}
        deploy:
            replicas: 1
            update_config:
                order: start-first
                parallelism: 1
                monitor: 15s
                failure_action: rollback
            labels:
                - traefik.enable=true

                - traefik.http.services.ytcg-showcase.loadbalancer.server.port=80

                - traefik.http.routers.ytcg-showcase.rule=Host(`ytcg.barlito.fr`)
                - traefik.http.routers.ytcg-showcase.entrypoints=http

                - traefik.http.routers.ytcg-showcase-secure.rule=Host(`ytcg.barlito.fr`)
                - traefik.http.routers.ytcg-showcase-secure.entrypoints=https
                - traefik.http.routers.ytcg-showcase-secure.tls=true
                - traefik.http.routers.ytcg-showcase-secure.tls.certresolver=letsencrypt
        networks:
            - traefik_traefik_proxy

networks:
    traefik_traefik_proxy:
        external: true
