version: '3.4'

services:
    nginx:
        # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#customization
        image: webdevops/php-nginx-dev:8.1
        volumes:
            - ./:/app
            - ./.docker/nginx/conf.d/default.conf:/opt/docker/etc/nginx/vhost.conf
        working_dir: /app
        environment:
            # PHP config
            # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#environment-variables
            PHP_DATE_TIMEZONE: "Europe/Paris"
            PHP_DISPLAY_ERRORS: "on"
            PHP_MEMORY_LIMIT: 512M
            PHP_MAX_EXECUTION_TIME: 7200
            PHP_REQUEST_TERMINATE_TIMEOUT: 7200
            PHP_POST_MAX_SIZE: 50M
            PHP_UPLOAD_MAX_FILESIZE: 50M
            PHP_OPCACHE_REVALIDATE_FREQ: 0
            php.xdebug.var_display_max_depth: 10
            php.xdebug.var_display_max_data: 2048
            XDEBUG_MODE: coverage
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.ytcg-showcase.loadbalancer.server.port=80

                - traefik.http.routers.ytcg-showcase.rule=Host(`ytcg.local.barlito.fr`)
                - traefik.http.routers.ytcg-showcase.entrypoints=http

                - traefik.http.routers.ytcg-showcase-secure.rule=Host(`ytcg.local.barlito.fr`)
                - traefik.http.routers.ytcg-showcase-secure.entrypoints=https
                - traefik.http.routers.ytcg-showcase-secure.tls=true
        networks:
            - traefik_traefik_proxy

networks:
    traefik_traefik_proxy:
        external: true
